apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cluster-config
  namespace: argocd
spec:
  destination:
    namespace: default
    server: "https://kubernetes.default.svc"
  project: default
  source:
    path: manifests/cluster
    repoURL: "https://github.com/Los-Externalistas/ArgoCD"
    targetRevision: main
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
